Traceback (most recent call last):
  File "D:\01_MProject\cp5_inline\inline_early_warning\sendmail_reprot.py", line 480, in <module>
    excel_question_save_addr = gen_question_sheet(point_name, time, car, part)
  File "D:\01_MProject\cp5_inline\inline_early_warning\sendmail_reprot.py", line 190, in gen_question_sheet
    series1 = chart.SeriesCollection().NewSeries()
  File "C:\Users\DATASY~1\AppData\Local\Temp\2\gen_py\3.6\00020813-0000-0000-C000-000000000046x0x1x7\_Chart.py", line 364, in SeriesCollection
    ret = self._oleobj_.InvokeTypes(68, LCID, 1, (9, 0), ((12, 17),),Index
pywintypes.com_error: (-2146827864, 'OLE error 0x800a01a8', None, None)
